import "./globals.css";

import { Toaster } from "@/components/shadcn/ui/toaster"

import { ThemeProvider } from "@/components/theme-provider"
import Header from "@/components/header";

export const metadata = {
  title: "talkabout",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark:bg-black" suppressHydrationWarning>
      <body>
        <ThemeProvider defaultTheme="dark" attribute="class">
          <Header />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html >
  );
}
